### ISSUE TITLE
[`example` tag] Appears broken for slice types

### ISSUE THREAD

**Issue by ortonomy** [wI2L/fizz#115]
In the docs [here](https://github.com/wI2L/fizz?tab=readme-ov-file#additional-tags), it explains that:

> You can use additional tags. Some will be interpreted by tonic, others will be exclusively used to enrich the OpenAPI specification.

> `example` - An example value to be used in OpenAPI specification. See [section below](https://github.com/wI2L/fizz?tab=readme-ov-file#Providing-Examples-for-Custom-Types) for the demonstration on how to provide example for custom types.

---

I've tried this:

```golang
type MultiPointWeatherRequest struct {
	Locations []string          `query:"locations[]" binding:"required" validate:"min=1" description:"Array of latitude,longitude pairs" explode:"true" example:"45.4215,-75.6972"`
	Start     *time.Time        `query:"start"`
	End       *time.Time        `query:"end"`
	Step      *models.PointStep `query:"step"`
}
```

Except the example is not being used in the open API specification that is generated:

```yaml
- name: locations[]
          in: query
          description: Array of latitude,longitude pairs
          schema:
            type: array
            items:
              type: string
            description: Array of latitude,longitude pairs
            minItems: 1
          style: form
          explode: true
```

What am I missing. I don't think this is a "custom type"?
