### ISSUE TITLE
HeaderTag now working in input struct

### ISSUE THREAD

**Issue by ipfans** [wI2L/fizz#58]
Hi, I try to use fizz to work with tonic, but I found HeaderTag not working for input struct. Because fizz not support OpenAPI security, so I tried to use header tag to some goal.

For example:

```go
type Info struct {
	Authorization string `header:"Authorization" description:"token" example:"Bear xxxxxxxx"`

	Name    string    `json:"name" validate:"required" example:"banana"`
	Origin  string    `json:"origin" validate:"required" description:"Country of origin of the fruit" enum:"ecuador,france,senegal,china,spain"`
	Price   float64   `json:"price" validate:"required" description:"Price in euros" example:"5.13"`
	AddedAt time.Time `json:"-" binding:"-" description:"Date of addition of the fruit to the market"`
}
```

The result become to :

```yaml
    RestInfo:
      type: object
      properties:
        Authorization:
          type: string
          description: Token
          example: Bear xxxxxxxx
        name:
          type: string
          example: banana
        origin:
          type: string
          description: Country of origin of the fruit
          enum:
          - ecuador
          - france
          - senegal
          - china
          - spain
        price:
          type: number
          description: Price in euros
          format: double
          example: 5.13
      required:
      - name
      - origin
      - price
```
